// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace NSSpain2017.iOS
{
	public partial class HeaderViewController : UIViewController
	{
		public HeaderViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
